Feature/add styles
IIC3585-2024/functional-js-group-04 pull request #1
Opened 2024-03-19 18:50 UTC by NatC18

Add basic markdown styles to html file.

2024-03-19 20:16 UTC, domingo2000 requested changes
Quizá podrías dejar que style() en vez de recibir el output path solo tome como input (opcional) el archivo css que vas a incluir. Así la api y el chaining de métodos te queda como. La idea es evitar pasar el `output_path` varias veces a nivel de la API del compilador.

```
compiler().read(input_path).tokenize().style(stylefile.css).write(output_path)

```

Donde stylefile.css es opcional y en la función `style()` se pase por defecto el archivo de estilos que creaste, así quizá después podemos dejar que se le pase un archivo css custom a nivel de CLI.

2024-03-19 20:17 UTC, domingo2000 commented
Por lo demás se ve weno!, Voy a probar ahora como se ve el markdown generado, me gustó mucho también poner por separado en el roadmap los estilos.

2024-03-19 20:19 UTC, domingo2000 commented
Respecto a como guardas el estilo, alfinal los estilos son solo un string que metes en el html, por lo que podría ser una variable de estado `_style` encapsulada (via closure de la función) dentro del compilador al igual como es `_output` actualmente.

2024-03-19 20:20 UTC, domingo2000 commented
PD: Se ve filete :rocket:
![image](https://github.com/IIC3585-2024/functional-js-group-04/assets/40220174/4097cb43-a48e-42eb-91dc-ca0a817a32db)

2024-03-19 22:05 UTC, Mgagol commented
Esta quedando bacán! Yo puedo ayudar más adelante a agregar estilos que vayan faltando 😄

2024-03-20 01:32 UTC, domingo2000 approved these changes
Lo shipeamos 🚀

2024-03-20 01:32 UTC, merged

2024-03-20 01:34 UTC, Mgagol approved these changes